### ISSUE TITLE
Contractor Management Total Cost Inconsistencies

### ISSUE THREAD

**Issue by MYPAVE** [afixia/mysites-tracker#14]
We just discovered issues regarding the Contractor Management report and the exported report as well as the outlook and summary displaying different information. It seems some may be including concrete repairs and some not, and others pulling the expense outlook rather than the immediate (when immediate is selected from report filters). We need these to show the same numbers without any inconsistencies...

**Site #0725 Inconsistencies** 
The Contractor Management report (immediates for 2021) displays total cost of:  $30,571.04
The exported report from Contractor Management displays total cost of:  $36,503
The actual immediate outlook for displays total cost of:  $36,502.64
Outlook summary shows the immediate outlook with a total cost of:  $30,571.04

**Site 2207 Inconsistencies**
The Contractor Management report (immediates for 2021) displays total cost of:  $776.08
The exported report from Contractor Management displays total cost of:  $198,590
The actual immediate outlook for displays total cost of:  $824.68
Outlook summary shows the immediate outlook with a total cost of:  $776.08

**Site 4178 Inconsistencies**
The Contractor Management report (immediates for 2021) displays total of:  $51,752.88
The exported report from Contractor Management displays total cost of:  $82,029
The actual immediate outlook for displays total cost of:  $51,752.88
Outlook summary shows the immediate outlook with a total cost of:  $51,752.88

**Comment by galtonafixia** [comment]
fixed.  This is deployed to the sandbox.  Will be deployed to production at next update.
