### ISSUE TITLE
Distress Map Sharing Not Working

### ISSUE THREAD

**Issue by MYPAVE** [afixia/mysites-tracker#16]
I am not able to share a distress map, nothing seems to populate in box to be copied (the link). 
This has to be fixed in the sandbox also so it works for the partners.

![1](https://user-images.githubusercontent.com/71840246/100015364-77ebf580-2d9d-11eb-94a8-5b006b52421f.png)
![2](https://user-images.githubusercontent.com/71840246/100015367-77ebf580-2d9d-11eb-9576-7ff27fe171a1.png)
![9](https://user-images.githubusercontent.com/71840246/100015368-78848c00-2d9d-11eb-8cbb-5e9e8183b299.png)

**Comment by galtonafixia** [comment]
fixed.  will be installed on next deployment
