### ISSUE TITLE
Images Not Automatically Opening When a Pin is Clicked On? 

### ISSUE THREAD

**Issue by MYPAVE** [afixia/mysites-tracker#17]
When media is clicked it opens media manager and then the images have to be individually double-clicked to open (this was changed previously to automatically open them to avoid a ton of clicks and saves time)

![1](https://user-images.githubusercontent.com/71840246/100015652-f052b680-2d9d-11eb-88f5-e683401f6340.png)
![2](https://user-images.githubusercontent.com/71840246/100015657-f21c7a00-2d9d-11eb-836d-60a6361eb649.png)

**Comment by galtonafixia** [comment]
fixed
