### ISSUE TITLE
Sorting Error in Site Management (Sort by Site PCI)

### ISSUE THREAD

**Issue by MYPAVE** [afixia/mysites-tracker#18]
I recall this being an issue a while back but I am still unable to sort the site list in Site Management by PCI. I am worried the partners will see this...

See below:

![1](https://user-images.githubusercontent.com/71840246/100015794-1d9f6480-2d9e-11eb-9faa-c05a3e5ced50.png)

**Comment by galtonafixia** [comment]
fixed. will be installed on next deployment
