### ISSUE TITLE
Pie Graph Not Filtering Sites Correctly on Map

### ISSUE THREAD

**Issue by MYPAVE** [afixia/mysites-tracker#19]
Pie graph not filtering sites correctly by PCI range on dashboard map. See below:

![1](https://user-images.githubusercontent.com/71840246/100020009-b5a04c80-2da4-11eb-9ea4-ea3c7b97b09e.png)
![2](https://user-images.githubusercontent.com/71840246/100020011-b638e300-2da4-11eb-88f0-f359d7ed1887.png)
![3](https://user-images.githubusercontent.com/71840246/100020013-b638e300-2da4-11eb-9f54-b988bfb902d0.png)

**Comment by galtonafixia** [comment]
fixed. will be installed on the next deployment
