### ISSUE TITLE
Contractor Management Incorrectly Filtering Sites by Search Based on Recommended/Selected and Outlook Type

### ISSUE THREAD

**Issue by MYPAVE** [afixia/mysites-tracker#2]
For example: Life Time #164 has an immediate outlook that is not "Selected" or "Recommended" (only 15 Year Selected), but it is still appearing when searched for only recommended, immediate outlooks in the repair year 2020 - see photos:

![Screenshot_1](https://user-images.githubusercontent.com/71840246/94176943-7023d980-fe5e-11ea-8027-e9e066be744b.jpg)

![Screenshot_10](https://user-images.githubusercontent.com/71840246/94177111-afeac100-fe5e-11ea-9e15-39b68c9c5dba.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/71840246/94177124-b416de80-fe5e-11ea-829a-f3e141973def.jpg)

**Comment by galtonafixia** [comment]
fixed: this will be included in the next release (after hours 9/30)
