### ISSUE TITLE
Overall Site PCI Not Adjusting When a Zone Type is Changed to Concrete? ("Include in PCI Calculation" is Unchecked)

### ISSUE THREAD

**Issue by MYPAVE** [afixia/mysites-tracker#6]
Site #146 has an overall site PCI of 85 in MyPave. Our separate PCI tracker is showing a PCI of 67. 

I discovered that it has a full concrete rear zone that was originally entered as asphalt, not concrete. When it is changed to concrete and the "include in PCI calculation" checkbox is unchecked I then looked at the full size PCI and it is still showing an 85 but it SHOULD be showing a 67. Does this not automatically calculate the asphalt zones?? What is the issue?

![Screenshot_4](https://user-images.githubusercontent.com/71840246/94598208-413da700-0254-11eb-8dfa-59b1b648b840.jpg)

![Screenshot_5](https://user-images.githubusercontent.com/71840246/94598300-5dd9df00-0254-11eb-869a-d58c1671a43d.jpg)

**Comment by galtonafixia** [comment]
The Whole Site PCI value is a manually entered value when the Site Assessment is created and not automatically (re)calculated. If the value is recognized to be in error, edit the Site Assessment enter the adjusted value.
