### ISSUE TITLE
Pie Chart & Bar Graph Not Matching Totals

### ISSUE THREAD

**Issue by MYPAVE** [afixia/mysites-tracker#8]
The pie chart and bar graph are not matching each other and we believe the bar chart is pulling assessed PCI rather than projected/live? Not sure what the pie is pulling now.

![Screenshot_48](https://user-images.githubusercontent.com/71840246/94853103-7c74dd00-03f0-11eb-89f3-e325e22b61a5.jpg)

![Screenshot_47](https://user-images.githubusercontent.com/71840246/94853104-7c74dd00-03f0-11eb-83bb-989e6485e33f.jpg)

**Comment by galtonafixia** [comment]
The value in the pie graph was mislabeled "site(s)" when it's actually a value in part of the percentage "%" calculation.  Updated in development, with be released in next deployment.
