### ISSUE TITLE
Timeline "Before" PCI Showing Current Year Instead of Proposed Construction Year

### ISSUE THREAD

**Issue by MYPAVE** [afixia/mysites-tracker#9]
The “before” PCI is showing current year rather than proposed construction year.  

For example on Life Time site #233 the PCI should show a 53 in year 2024 when the site is to be constructed but it is showing a 70 (which is the current 2020 year PCI).

![1](https://user-images.githubusercontent.com/71840246/94856201-3d955600-03f5-11eb-809a-b6e3bf2a3e93.jpg)

![2](https://user-images.githubusercontent.com/71840246/94856205-40904680-03f5-11eb-9cfb-a5e9a447bc3b.jpg)

**Comment by galtonafixia** [comment]
addressed in another update. deployed
